#!/bin/bash

#SBATCH --cpus-per-task=20
#SBATCH --job-name=ext_smS
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=2
#SBATCH --qos=gpu_free
#SBATCH --mem=350GB
#SBATCH --time=12:00:00
#SBATCH --chdir /scratch/izar/xugao/trainLogs
#SBATCH --output=/scratch/izar/xugao/trainLogs/una_ext_smS_1_%j.out
#SBATCH --error=/scratch/izar/xugao/trainLogs/una_ext_smS_1_%j.err

module load gcc cuda
echo "hello from 'hostname'"

source /home/xugao/venvs/venv-for-demo/bin/activate

cd /home/xugao/gitRepo/swapping-autoencoder-pytorch

python -m experiments --name nightVision --cmd train --id nightVision_unaligned_extreme_smallSize

echo "bye from 'hostname'"


